version: '3'

services:
  php:
    image: php:7.2-apache
    volumes:
      - ./public:/var/www/html
  browsersync:
    build: browsersync
    command: browser-sync start --config ./browsersync/docker-bs-conf.js
    volumes:
      - .:/app
    ports:
      - "3001:3001"
      - "3000:3000"